server {
    listen 80;
    server_name it-hackathon-team05.mephi.ru;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name it-hackathon-team05.mephi.ru;

    ssl_certificate /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;

    location ^~ /admin/api/ {
        proxy_pass http://backend_admin_api/admin/api/;
        proxy_http_version 1.1;
        proxy_cache off;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" always;
        add_header Pragma "no-cache" always;
        add_header Expires "0" always;
        proxy_buffering off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    location = /admin/api {
        return 301 /admin/api/;
    }

    location = /api {
        return 301 /api/;
    }

    location ^~ /api/ {
        proxy_pass http://backend_api/api/;
        proxy_http_version 1.1;
	
	proxy_cache off;

	add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" always;
	add_header Pragma "no-cache" always;
	add_header Expires "0" always;

	proxy_buffering off;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    location  ^~ /admin-panel/ {
        limit_req zone=general_limit burst=20 nodelay;
        
        #rewrite ^/admin-panel/(.*)$ /$1 break;
        
        proxy_pass http://moderator_app;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_cache_bypass $http_upgrade;
        
        proxy_redirect off;
        
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
    
    location = /admin-panel {
        return 301 /admin-panel/;
    }

    location / {
        proxy_pass http://hakaton_app/;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
