# Upstream серверы для балансировки нагрузки

# Backend API (NestJS)
upstream backend_api {
    server backend-app:3000;
    keepalive 32;
}

upstream backend_admin_api {
    server backend-admin-app:3000;
    keepalive 32;
}

# Hakaton frontend (главное приложение)
upstream hakaton_app {
    server hakaton-app:80;
    keepalive 32;
}

# Moderator frontend
upstream moderator_app {
    server frontend-admin-app:80;
    keepalive 32;
}

# Chatty app
upstream chatty_app {
    server chatty-app:3000;
    keepalive 32;
}
